"""changed task to link to comment

Revision ID: 1efc0c7e4073
Revises: ce6b6651cbe8
Create Date: 2021-02-17 17:27:16.793804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efc0c7e4073'
down_revision = 'ce6b6651cbe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tk_comment', sa.Integer(), nullable=True),
    sa.Column('tk_duedate', sa.DateTime(), nullable=True),
    sa.Column('tk_notify', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tk_comment'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
