"""add media, kit and funding

Revision ID: 2430814ba739
Revises: 1b505e0e8477
Create Date: 2020-05-20 18:28:40.147692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2430814ba739'
down_revision = '1b505e0e8477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_cohortid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kit_cohortid'], ['cohort.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    op.drop_table('kit')
    # ### end Alembic commands ###
