"""order tables

Revision ID: 24ea9457c37d
Revises: 517a24dd3313
Create Date: 2021-04-26 15:56:52.395266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ea9457c37d'
down_revision = '517a24dd3313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('order_cohort', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['order_cohort'], ['cohort.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('order_qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['stock_item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('order')
    # ### end Alembic commands ###
