"""added Probation Services

Revision ID: 4311b305a068
Revises: b3fe1c74d97b
Create Date: 2020-09-03 13:58:33.763563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4311b305a068'
down_revision = 'b3fe1c74d97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prob_name', sa.String(length=120), nullable=True),
    sa.Column('prob_town', sa.String(length=40), nullable=True),
    sa.Column('prob_postcode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('probation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_probation_prob_name'), ['prob_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_probation_prob_postcode'), ['prob_postcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_probation_prob_town'), ['prob_town'], unique=False)

    with op.batch_alter_table('cohort', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coh_probid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_cohort_probation', 'probation', ['coh_probid'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prob_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_comment_probation', 'probation', ['prob_id'], ['id'])

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('con_probation', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_contact_probation', 'probation', ['con_probation'], ['id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('med_probid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_media_probation', 'probation', ['med_probid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('med_probid')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('con_probation')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prob_id')

    with op.batch_alter_table('cohort', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('coh_probid')

    with op.batch_alter_table('probation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_probation_prob_town'))
        batch_op.drop_index(batch_op.f('ix_probation_prob_postcode'))
        batch_op.drop_index(batch_op.f('ix_probation_prob_name'))

    op.drop_table('probation')
    # ### end Alembic commands ###
