"""longer phone field

Revision ID: 48a5a0397c82
Revises: bc435e393687
Create Date: 2020-11-03 12:37:51.554760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a5a0397c82'
down_revision = 'bc435e393687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.alter_column('clb_badge',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('con_phone',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('con_phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.alter_column('clb_badge',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###
