"""empty message

Revision ID: 49de17a25aac
Revises: 144075fc0b94
Create Date: 2021-11-16 17:07:06.200028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49de17a25aac'
down_revision = '144075fc0b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kit_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_cohortid', sa.Integer(), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_cohortid'], ['cohort.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kit_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=40), nullable=True),
    sa.Column('order_qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item'], ['stock.sku'], ),
    sa.ForeignKeyConstraint(['order_id'], ['kit_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kit_item')
    op.drop_table('kit_order')
    # ### end Alembic commands ###
