"""stock tables

Revision ID: 517a24dd3313
Revises: 1efc0c7e4073
Create Date: 2021-04-23 14:53:19.894575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517a24dd3313'
down_revision = '1efc0c7e4073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('si_name', sa.String(length=20), nullable=True),
    sa.Column('si_desc', sa.String(length=120), nullable=True),
    sa.Column('si_size', sa.String(length=10), nullable=True),
    sa.Column('si_sku', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('si_sku')
    )
    op.create_table('stock',
    sa.Column('si_id', sa.String(length=12), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['si_id'], ['stock_item.id'], ),
    sa.PrimaryKeyConstraint('si_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('stock_item')
    # ### end Alembic commands ###
