"""added upshot column

Revision ID: 5c084caa42b5
Revises: c08ebd7931fc
Create Date: 2022-10-14 11:27:13.356525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c084caa42b5'
down_revision = 'c08ebd7931fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prison', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prs_upshot', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prison', schema=None) as batch_op:
        batch_op.drop_column('prs_upshot')

    # ### end Alembic commands ###
