"""new link table

Revision ID: 5dfff7a4f7bb
Revises: 48a5a0397c82
Create Date: 2021-01-20 12:02:19.207390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfff7a4f7bb'
down_revision = '48a5a0397c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_club', sa.Integer(), nullable=True),
    sa.Column('link_prs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_club'], ['club.id'], ),
    sa.ForeignKeyConstraint(['link_prs'], ['prison.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
