"""prison additional fields

Revision ID: 7031362a56c2
Revises: d95a7e5d9328
Create Date: 2020-08-19 17:08:08.159469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7031362a56c2'
down_revision = 'd95a7e5d9328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prison', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prs_postcode', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_prison_prs_postcode'), ['prs_postcode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prison', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prison_prs_postcode'))
        batch_op.drop_column('prs_postcode')

    # ### end Alembic commands ###
