"""stock timestamp

Revision ID: 70bec41790cc
Revises: f4c8ed2d037c
Create Date: 2021-04-28 14:25:32.568530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bec41790cc'
down_revision = 'f4c8ed2d037c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('last_update')

    # ### end Alembic commands ###
