"""contacts, categories, prisons

Revision ID: 9b3dcd4b8d33
Revises: a7e9861bfc48
Create Date: 2020-05-14 14:46:49.552759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3dcd4b8d33'
down_revision = 'a7e9861bfc48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_desc', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_cat_desc'), 'category', ['cat_desc'], unique=True)
    op.create_table('prison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prs_name', sa.String(length=120), nullable=True),
    sa.Column('prs_town', sa.String(length=40), nullable=True),
    sa.Column('prs_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prs_category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prison_prs_name'), 'prison', ['prs_name'], unique=True)
    op.create_index(op.f('ix_prison_prs_town'), 'prison', ['prs_town'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('con_firstname', sa.String(length=64), nullable=True),
    sa.Column('con_surname', sa.String(length=64), nullable=True),
    sa.Column('con_email', sa.String(length=120), nullable=True),
    sa.Column('con_phone', sa.String(length=11), nullable=True),
    sa.Column('con_club', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['con_club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_con_email'), 'contact', ['con_email'], unique=True)
    op.create_index(op.f('ix_contact_con_phone'), 'contact', ['con_phone'], unique=False)
    op.create_index(op.f('ix_contact_con_surname'), 'contact', ['con_surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_con_surname'), table_name='contact')
    op.drop_index(op.f('ix_contact_con_phone'), table_name='contact')
    op.drop_index(op.f('ix_contact_con_email'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_prison_prs_town'), table_name='prison')
    op.drop_index(op.f('ix_prison_prs_name'), table_name='prison')
    op.drop_table('prison')
    op.drop_index(op.f('ix_category_cat_desc'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
