"""added user to task

Revision ID: a529af21bb61
Revises: 1efc0c7e4073
Create Date: 2021-06-16 11:32:06.415408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a529af21bb61'
down_revision = '1efc0c7e4073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tk_user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('None', 'user', ['tk_user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tk_user')

    # ### end Alembic commands ###
