"""additional field for cohort freq

Revision ID: aaec4fa784b1
Revises: 49de17a25aac
Create Date: 2022-05-17 11:30:22.006426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaec4fa784b1'
down_revision = '49de17a25aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cohort', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coh_frequency', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cohort', schema=None) as batch_op:
        batch_op.drop_column('coh_frequency')

    # ### end Alembic commands ###
