"""Made change to Category

Revision ID: b5557dcd8579
Revises: 9b3dcd4b8d33
Create Date: 2020-05-15 14:13:36.919721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5557dcd8579'
down_revision = '9b3dcd4b8d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('cat_shortcode', sa.String(length=3), nullable=True))
    op.create_index(op.f('ix_category_cat_shortcode'), 'category', ['cat_shortcode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_cat_shortcode'), table_name='category')
    op.drop_column('category', 'cat_shortcode')
    # ### end Alembic commands ###
