"""new comment type

Revision ID: bc435e393687
Revises: e76eebbf7c05
Create Date: 2020-11-03 11:33:21.119213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc435e393687'
down_revision = 'e76eebbf7c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('body',
                              existing_type=sa.VARCHAR(length=140),
                              type_=sa.Text(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('body',
                              existing_type=sa.Text(),
                              type_=sa.VARCHAR(length=140),
                              existing_nullable=True)

    # ### end Alembic commands ###
