"""2 separate link tables

Revision ID: ce6b6651cbe8
Revises: 48a5a0397c82
Create Date: 2021-02-15 16:09:09.878734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6b6651cbe8'
down_revision = '48a5a0397c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prob_links',
    sa.Column('prob_link_clb_id', sa.Integer(), nullable=True),
    sa.Column('link_prob_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_prob_id'], ['probation.id'], ),
    sa.ForeignKeyConstraint(['prob_link_clb_id'], ['club.id'], )
    )
    op.create_table('prs_links',
    sa.Column('prs_link_clb_id', sa.Integer(), nullable=True),
    sa.Column('link_prs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_prs_id'], ['prison.id'], ),
    sa.ForeignKeyConstraint(['prs_link_clb_id'], ['club.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prs_links')
    op.drop_table('prob_links')
    # ### end Alembic commands ###
