"""prison additional fields

Revision ID: d724dedbe3cd
Revises: 7031362a56c2
Create Date: 2020-08-19 17:17:49.862725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd724dedbe3cd'
down_revision = '7031362a56c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('con_prison', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_prison_contact', 'prison', ['con_prison'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('con_prison')

    # ### end Alembic commands ###
