"""stock keeping system

Revision ID: e76eebbf7c05
Revises: e9a3cce782e7
Create Date: 2020-10-21 12:29:33.458188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76eebbf7c05'
down_revision = 'e9a3cce782e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=True),
    sa.Column('stock_desc', sa.String(length=40), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_sku'), ['sku'], unique=True)

    op.create_table('kit_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=True),
    sa.Column('order_qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item'], ['stock.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kit_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_cohortid', sa.Integer(), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('order_item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_cohortid'], ['cohort.id'], ),
    sa.ForeignKeyConstraint(['order_item'], ['kit_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kit_order')
    op.drop_table('kit_item')
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_sku'))

    op.drop_table('stock')
    # ### end Alembic commands ###
