"""new stockitem and inventory tables

Revision ID: f41204e3340f
Revises: a529af21bb61
Create Date: 2021-07-28 15:49:32.502670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41204e3340f'
down_revision = 'a529af21bb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_sku', sa.String(length=12), nullable=True),
    sa.Column('item_desc', sa.String(length=40), nullable=True),
    sa.Column('item_size', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_item_item_sku'), ['item_sku'], unique=True)

    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=12), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['stock_item.item_sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_item_item_sku'))

    op.drop_table('stock_item')
    # ### end Alembic commands ###
