"""index S_items

Revision ID: f4c8ed2d037c
Revises: 24ea9457c37d
Create Date: 2021-04-28 12:33:22.036486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c8ed2d037c'
down_revision = '24ea9457c37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_item_si_sku'), ['si_sku'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_item_si_sku'))

    # ### end Alembic commands ###
