"""kit table issues

Revision ID: 199332910c99
Revises: d509b4c4bc89
Create Date: 2020-05-28 16:53:24.905006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199332910c99'
down_revision = 'd509b4c4bc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'media', ['med_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'funding', ['fnd_id'], ['id'])
    op.add_column('kit', sa.Column('kit_date', sa.DateTime(), nullable=True))
    op.add_column('kit', sa.Column('kit_numLarge', sa.Integer(), nullable=True))
    op.add_column('kit', sa.Column('kit_numMedium', sa.Integer(), nullable=True))
    op.add_column('kit', sa.Column('kit_numSmall', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_kit_kit_date'), 'kit', ['kit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kit_kit_date'), table_name='kit')
    op.drop_column('kit', 'kit_numSmall')
    op.drop_column('kit', 'kit_numMedium')
    op.drop_column('kit', 'kit_numLarge')
    op.drop_column('kit', 'kit_date')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
