"""adding cohorts and comments

Revision ID: 1b505e0e8477
Revises: b5557dcd8579
Create Date: 2020-05-15 17:02:02.677893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b505e0e8477'
down_revision = 'b5557dcd8579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coh_desc', sa.String(length=40), nullable=True),
    sa.Column('coh_clubid', sa.Integer(), nullable=True),
    sa.Column('coh_prisonid', sa.Integer(), nullable=True),
    sa.Column('coh_startDate', sa.DateTime(), nullable=True),
    sa.Column('coh_endDate', sa.DateTime(), nullable=True),
    sa.Column('coh_deliveryDate', sa.DateTime(), nullable=True),
    sa.Column('coh_tpi', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['coh_clubid'], ['club.id'], ),
    sa.ForeignKeyConstraint(['coh_prisonid'], ['prison.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_table('comment')
    op.drop_table('cohort')
    # ### end Alembic commands ###
