"""new kit

Revision ID: 7df5a40b684d
Revises: b8288f5d5e0d
Create Date: 2020-05-28 18:51:53.162217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df5a40b684d'
down_revision = 'b8288f5d5e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'media', ['med_id'], ['id'])
        batch_op.create_foreign_key(None, 'funding', ['fnd_id'], ['id'])

    with op.batch_alter_table('kit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kit_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('kit_numLarge', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kit_numMedium', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kit_numSmall', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_kit_kit_date'), ['kit_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kit_kit_date'))
        batch_op.drop_column('kit_numSmall')
        batch_op.drop_column('kit_numMedium')
        batch_op.drop_column('kit_numLarge')
        batch_op.drop_column('kit_date')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
