"""empty message

Revision ID: a7e9861bfc48
Revises: 32b1e6fc064f
Create Date: 2020-05-14 10:46:16.089145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e9861bfc48'
down_revision = '32b1e6fc064f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_division_div_desc', table_name='division')
    op.create_index(op.f('ix_division_div_desc'), 'division', ['div_desc'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_division_div_desc'), table_name='division')
    op.create_index('ix_division_div_desc', 'division', ['div_desc'], unique=False)
    # ### end Alembic commands ###
