"""empty message

Revision ID: d509b4c4bc89
Revises: 2430814ba739
Create Date: 2020-05-21 12:00:19.951245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd509b4c4bc89'
down_revision = '2430814ba739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('med_clubid', sa.Integer(), nullable=True),
    sa.Column('med_prisonid', sa.Integer(), nullable=True),
    sa.Column('med_date', sa.DateTime(), nullable=True),
    sa.Column('med_medium', sa.String(length=40), nullable=True),
    sa.Column('med_publication', sa.String(length=40), nullable=True),
    sa.Column('med_link', sa.String(length=120), nullable=True),
    sa.Column('med_author', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['med_clubid'], ['club.id'], ),
    sa.ForeignKeyConstraint(['med_prisonid'], ['prison.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fnd_cohort', sa.Integer(), nullable=True),
    sa.Column('fnd_date', sa.DateTime(), nullable=True),
    sa.Column('fnd_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fnd_cohort'], ['cohort.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_fnd_date'), 'funding', ['fnd_date'], unique=False)
    op.add_column('comment', sa.Column('fnd_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('med_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'media', ['med_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'funding', ['fnd_id'], ['id'])
    op.add_column('kit', sa.Column('kit_date', sa.DateTime(), nullable=True))
    op.add_column('kit', sa.Column('kit_numLarge', sa.Integer(), nullable=True))
    op.add_column('kit', sa.Column('kit_numMedium', sa.Integer(), nullable=True))
    op.add_column('kit', sa.Column('kit_numSmall', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_kit_kit_date'), 'kit', ['kit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kit_kit_date'), table_name='kit')
    op.drop_column('kit', 'kit_numSmall')
    op.drop_column('kit', 'kit_numMedium')
    op.drop_column('kit', 'kit_numLarge')
    op.drop_column('kit', 'kit_date')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'med_id')
    op.drop_column('comment', 'fnd_id')
    op.drop_index(op.f('ix_funding_fnd_date'), table_name='funding')
    op.drop_table('funding')
    op.drop_table('media')
    # ### end Alembic commands ###
